---
title: "car"
author: "David Criado Ramón"
date: "13/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(magrittr)
library(ggplot2)
library(VIM)
library(car)
```
```{r}
df.car_spec_data <- read_csv("https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2015/01/auto-snout_car-specifications_COMBINED.txt")
```
Ver missing values
```{r}
aggr_plot <-  aggr(df.car_spec_data, col=c('blue','red'), numbers=TRUE,
sortVars=TRUE, labels=names(df.car_spec_data), cex.axis=.7, gap=3,
ylab=c("Histogram of missing data","Pattern"))
```

Retiramos la variable que tiene demasiados missing values.

```{r}
ggplot(df.car_spec_data, aes(x=horsepower_bhp, y=top_speed_mph)) +
  geom_point(alpha=0.4, color="blue")
```

```{r}
ggplot(df.car_spec_data, aes(x=top_speed_mph)) + geom_histogram()
```

```{r}
cars149159 <- df.car_spec_data %>% filter(between(top_speed_mph, 149, 159))
ggplot(cars149159, aes(x=top_speed_mph)) + geom_bar()
```

```{r}
ggplot(df.car_spec_data, aes(x=top_speed_mph)) + geom_histogram(fill="blue") + facet_wrap(~decade)
```

```{r}
df.car_spec_data %>% filter(top_speed_mph==155 & year>1990) %>%
                     group_by(make_nm) %>%
                     count() %>%
                     arrange(desc(n))
```
```{r}
ggplot(df.car_spec_data, aes(x=horsepower_bhp, y=top_speed_mph)) +
  geom_point(alpha=.7, col="blue") + facet_wrap(.~decade)
```

```{r}
ggplot(data=df.car_spec_data, aes(x=year,
y=df.car_spec_data$top_speed_mph)) +
geom_point(alpha=.35, size=4.5, color="#880011", position =
position_jitter()) +
scale_x_discrete(breaks =
c("1950","1960","1970","1980","1990","2000","2010")) +
ggtitle("Car Top Speeds by Year") +
labs(x="Year" ,y="Top Speed\nmph")
```
```{r}
topspeeds <-  df.car_spec_data %>% 
              group_by(year) %>%
              summarize(max_speed= max(top_speed_mph, na.rm=T))
ggplot(topspeeds, aes(x=year, y=max_speed)) + 
  geom_point(col="green") + geom_smooth(method="auto")
```
```{r}
ggplot(df.car_spec_data, aes(x=car_0_60_time_seconds, y=horsepower_bhp)) + geom_point() + geom_smooth()
```
```{r}
df.car_spec_data %>% arrange(desc(top_speed_mph)) %>% 
                     select(car_full_nm, top_speed_mph) %>%
                     head(10) %>%
                     ggplot(aes(x=top_speed_mph)) + geom_bar()
```
# Kaggle Bicis

```{r}
test <- read.csv("test.csv")
train <- read.csv("train.csv")
test$registered <- 0
test$casual <- 0
test$count <- 0
df <- rbind(train, test)
```

```{r}
scatterplotMatrix(df[,6:length(df)])
```

```{r}
aggr_plot <-  aggr(df, col=c('blue','red'), numbers=TRUE,
sortVars=TRUE, labels=names(df), cex.axis=.7, gap=3,
ylab=c("Histogram of missing data","Pattern"))
```

